export const plans = [
  {
    id: "free",
    name: "Free",
    price: 0,
    chars: 1000,
    description: "Hear your own words.",
    features: [
      "1 000 one-time credits",
      "All 30 voices",
      "WAV downloads",
      "No credit card",
      "100 MB · recordings kept for 7 days",
    ],
  },
  {
    id: "starter",
    name: "Starter",
    price: 12,
    chars: 30000,
    description: "For your first creative stories.",
    features: [
      "30 000 credits per month",
      "All 30 voices",
      "Two-host podcasts",
      "Shared audio & video balance",
      "2 GB · recordings kept for 30 days",
    ],
  },
  {
    id: "creator",
    name: "Creator",
    price: 29,
    chars: 100000,
    description: "For content with its own voice.",
    features: [
      "100 000 credits per month",
      "Everything in Starter",
      "Up to 10,000 characters per project",
      "Saved projects and versions",
      "10 GB · recordings kept for 90 days",
    ],
  },
  {
    id: "studio",
    name: "Studio",
    price: 59,
    chars: 250000,
    description: "For your everyday creative workflow.",
    features: [
      "250 000 credits per month",
      "Everything in Creator",
      "Ads and client projects",
      "Script exports",
      "20 GB · recordings kept for 180 days",
    ],
  },
] as const;
export type PlanId = (typeof plans)[number]["id"];
export const voiceList = [
  ["mila", "Mila", "Female", "Clear and fresh", "Coral"],
  ["boris", "Boris", "Male", "Lively and playful", "Blue"],
  ["nikola", "Nikola", "Male", "Calm and informative", "Lilac"],
  ["elena", "Elena", "Female", "Confident and direct", "Green"],
  ["kaloyan", "Kaloyan", "Male", "Energetic and powerful", "Yellow"],
  ["daria", "Daria", "Female", "Youthful and light", "Coral"],
  ["ivan", "Ivan", "Male", "Full and decisive", "Blue"],
  ["ralitsa", "Ralitsa", "Female", "Airy and soft", "Lilac"],
  ["teodora", "Teodora", "Female", "Casual", "Green"],
  ["yana", "Yana", "Female", "Bright and expressive", "Yellow"],
  ["stefan", "Stefan", "Male", "Gentle and soft", "Coral"],
  ["alexander", "Alexander", "Male", "Mature and articulate", "Blue"],
  ["daniel", "Daniel", "Male", "Casual and calm", "Lilac"],
  ["georgi", "Georgi", "Male", "Smooth and soft", "Green"],
  ["petya", "Petya", "Female", "Clear and smooth", "Yellow"],
  ["viktoria", "Victoria", "Female", "Clean and expressive", "Coral"],
  ["hristo", "Hristo", "Male", "Husky and distinctive", "Blue"],
  ["martin", "Martin", "Male", "Informative", "Lilac"],
  ["simona", "Simona", "Female", "Energetic and fresh", "Green"],
  ["dimitar", "Dimitar", "Male", "Mature and full", "Yellow"],
  ["neli", "Neli", "Female", "Soft and delicate", "Coral"],
  ["anton", "Anton", "Male", "Even and clear", "Blue"],
  ["plamen", "Plamen", "Male", "Calm and mature", "Lilac"],
  ["irina", "Irina", "Female", "Direct and articulate", "Green"],
  ["ivaylo", "Ivaylo", "Male", "Friendly", "Yellow"],
  ["todor", "Todor", "Male", "Casual", "Coral"],
  ["desislava", "Desislava", "Female", "Gentle and bright", "Blue"],
  ["svetoslav", "Svetoslav", "Male", "Lively and expressive", "Lilac"],
  ["kristina", "Kristina", "Female", "Soft and smooth", "Green"],
  ["maria", "Maria", "Female", "Warm and welcoming", "Yellow"],
].map(([id, name, gender, tone, color]) => ({ id, name, gender, tone, color }));
export const sampleSentence =
  "Sometimes all it takes is one voice to bring a story to life — let us tell yours today.";
export const modes = [
  {
    id: "tts",
    name: "Text to speech",
    description: "From written to spoken.",
    icon: "speech",
  },
  {
    id: "podcast",
    name: "Podcast",
    description: "Two voices. One great conversation.",
    icon: "podcast",
  },
  {
    id: "voiceover",
    name: "Voiceover",
    description: "A voice for videos, ads, and lessons.",
    icon: "video",
  },
] as const;
